# Generated by Django 6.0.5 on 2026-05-07 07:29

import django.db.models.deletion
import main_app.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BH', validators=[main_app.models.only_bh_numbers]),
        ),
    ]
