# Generated by Django 6.0.5 on 2026-05-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_owner_user_alter_owner_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.IntegerField()),
                ('species', models.CharField(max_length=80)),
                ('breed', models.CharField(max_length=80)),
                ('isFixed', models.BooleanField()),
                ('friends', models.ManyToManyField(blank=True, to='main_app.pet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main_app.owner')),
            ],
        ),
    ]
