# Generated by Django 6.0.5 on 2026-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
