# Generated by Django 6.0.5 on 2026-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('mustReserve', models.BooleanField()),
                ('attendees', models.ManyToManyField(blank=True, to='main_app.owner')),
            ],
        ),
    ]
