# Generated by Django 6.0.5 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_owner_city_alter_pet_breed_alter_pet_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_event', to='main_app.owner'),
            preserve_default=False,
        ),
    ]
