# Generated by Django 6.0.5 on 2026-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_city_event_location_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
