# Generated by Django 6.0.5 on 2026-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mustReserve',
            new_name='hasFees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
