# Generated by Django 6.0.5 on 2026-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_event_date_time_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='main_app.owner'),
        ),
    ]
