# Generated by Django 6.0.5 on 2026-05-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_owner_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='followers', to='main_app.pet'),
        ),
    ]
